Add rosaction CLI tool
ros/actionlib pull request #115
Opened 2018-08-09 21:24 UTC by maximkulkin

Added rosaction CLI tool to list/get info/send actions, similar to rosservice tool.

Supported commands:
* `rosaction list`
* `rosaction info /action`
* `rosaction type /action`
* `rosaction type /action goal`
* `rosaction type /action feedback`
* `rosaction type /action result`
* `rosaction send /action "goal: 123"`

Closes #44

2018-08-23 22:44 UTC, maximkulkin commented
Guys this PR is ready and passing. I'm a bit concerned on the whole "wait" thing in tests: you basically send something and wait for response and that waiting has a timeout but if system is under load, it might not be quick to respond and the test will fail. Although this approach seems to be ubiquitous. Otherwise please advise.

2018-09-18 05:35 UTC, maximkulkin commented
This PR is ready to be merged.

2018-11-11 04:08 UTC, maximkulkin commented
Ping! Can we get this PR merged?

2019-04-04 12:44 UTC, felixvd commented
Just a +1 to say that if this works as expected it's a great addition that most users probably simply expect to be there (like I did, once).

2019-04-15 02:44 UTC, fujitatomoya commented
+1, i believe that conceptually action should have own interface to user.

2019-04-15 16:25 UTC, mjcarroll requested changes
Sorry, I started this review an never submitted it.

2019-04-15 16:25 UTC, mjcarroll commented on CMakeLists.txt
> +catkin_install_python(PROGRAMS tools/rosaction tools/axclient.py tools/axserver.py tools/dynamic_action.py tools/library.py
You are installing some files that don't seem to be part of this PR.  Were these intended to be here?

2019-04-15 16:25 UTC, mjcarroll commented on src/actionlib/utils.py
> +import rosgraph
I believe that this is conceptually similar enough to the McGill code that it warrants including the full MIT license header as well as their copyright statement and a link to the original repository.

2020-12-08 06:03 UTC, mmoerdijk commented on CMakeLists.txt
> +catkin_install_python(PROGRAMS tools/rosaction tools/axclient.py tools/axserver.py tools/dynamic_action.py tools/library.py
I don't think he is, as hey only added the `tools/rosaction` and the env hooks for it.

2020-12-08 06:05 UTC, mmoerdijk commented on src/actionlib/utils.py
> +import rosgraph
I agree @maximkulkin could you dust off this MR and add the [license of mcgill](https://github.com/mcgill-robotics/rosaction/blob/master/LICENSE) to the files?

2022-08-17 19:38 UTC, closed without merging