Trigger goal cancelling depending on client state. Fixes #126
ros/actionlib pull request #130
Opened 2019-03-22 06:32 UTC by martiniil

This prevents an undesirable transition from DONE to WAITING_FOR_CANCEL_ACK.
See https://github.com/ros/actionlib/issues/126

2019-05-20 09:52 UTC, jschleicher commented
@mjcarroll This check is copied from cpp to the python client (see #126). Please review.

2019-05-20 09:52 UTC, jschleicher approved these changes

2020-07-27 13:35 UTC, Timple commented
I am also getting the `Received comm state PREEMPTING when in simple state DONE with SimpleActionClient` errors. 
Is anything holding this PR back?

2020-08-07 19:55 UTC, zhuang42 commented
> I am also getting the `Received comm state PREEMPTING when in simple state DONE with SimpleActionClient` errors.
> Is anything holding this PR back?

+1

2020-08-10 07:43 UTC, jschleicher approved these changes

2020-08-24 08:21 UTC, Timple commented
Thanks for the approval! Who has the authority to hit the merge button?

2020-10-12 12:31 UTC, Timple commented
A subtle ping to @mjcarroll because he did the last release and probably has some rights here :slightly_smiling_face:

2024-07-23 10:46 UTC, Timple commented
The ping is broken :cry:

2025-04-23 19:29 UTC, sloretz requested changes
Thank you for the PR!

[ROS Noetic will reach end-of-life on May 31st, 2025](https://discourse.ros.org/t/ros-noetic-end-of-life-may-31-2025/43160). Every change comes with a risk of introducing regressions, and there isn't much time left to fix them. To make sure this PR doesn't introduce any regressions please:

* Describe how you tested this change
* Recruit at least one more person to review this PR and try it out on their system

2025-04-23 19:29 UTC, sloretz commented on CHANGELOG.rst
> +* [bugfix] trigger goal cancelling depending on client state (`#126 <https://github.com/ros/actionlib/issues/126>`_)
Please remove the changes to CHANGELOG.rst

2025-05-31 17:44 UTC, sloretz commented
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)

2025-05-31 17:44 UTC, closed without merging