Fix sim time wait (#137)
ros/actionlib pull request #138
Opened 2019-05-20 13:15 UTC by beetleskin

fixes #137

2019-05-20 20:41 UTC, simon-rotter requested changes

2019-05-20 20:41 UTC, simon-rotter commented on src/actionlib/action_client.py
>      ## the user wait until the network connection to the server is negotiated
Would be great if we could use this diff to update also the documentation.

2019-05-26 20:58 UTC, beetleskin commented
CI seems broken .. anyone around?

2019-12-13 17:09 UTC, beetleskin commented
anyone .. still alive here?

2019-12-16 05:20 UTC, fujitatomoya approved these changes

2019-12-16 05:20 UTC, fujitatomoya commented
@beetleskin 

LGTM

2019-12-17 18:04 UTC, beetleskin commented
the cpp SimpleActionClient has the same problem, right?

2025-04-25 18:08 UTC, sloretz commented
Thank you for the PR!

Unfortunately I don't think we should merge this one. It's not clear to me that this timeout should be using wall time instead of sim time. Given that [ROS Noetic will reach end-of-life on May 31st, 2025](https://discourse.ros.org/t/ros-noetic-end-of-life-may-31-2025/43160), I'm going to leave the behavior as is.

2025-04-25 18:08 UTC, closed without merging